package product;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.4.5
 * 2021-12-10T22:09:33.862+03:00
 * Generated source version: 3.4.5
 *
 */
@WebService(targetNamespace = "http://product", name = "ProductGateway")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ProductGateway {

    @WebMethod(operationName = "Product", action = "http://product.request")
    @WebResult(name = "ProductResponse", targetNamespace = "http://product", partName = "ProductResponse")
    public ProductResponse product(

        @WebParam(partName = "ProductRequest", name = "ProductRequest", targetNamespace = "http://product")
        ProductRequest productRequest
    );
}
